name: figures
version: 1.0.1
description: A Dart package for using Unicode symbols with Windows CMD fallbacks.
environment:
  sdk: '>=2.0.0 <3.0.0'
author: Saran Tanpituckpong <sarunta@gmail.com>
repository: https://github.com/gluons/figures.dart
issue_tracker: https://github.com/gluons/figures.dart/issues
homepage: https://github.com/gluons/figures.dart
dev_dependencies:
  pedantic: ^1.7.0
